### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by danieland** [shopgun/verso-browser#8]
https://github.com/shopgun/verso-browser/blob/95a8a0389377ecaaa025a1873504ef8543ed3950/vendor/hammer.js#L1013

Hi guys! Could you introduce a nullcheck here or do you see problems with this?

**Comment by klarstrup** [comment]
Any way for me to reproduce this error? We can add that check for sure but I'm curious how the situation occurred in the first place

**Comment by danieland** [comment]
I'm not 100% sure it reproduces every single time but it's pretty close - I can almost always trigger it with something like this:

1. Visit https://www.jemogfix.dk/avisen/
2. Open the catalog
3. Close the catalog
4. Open the catalog
5. Press "Next" arrow

EDIT: every "Next" click from here on should keep triggering the error each time
EDIT2: there are no visible errors other than the one in console which is picked up by our Application Insights many times a day (1000+)

**Comment by danieland** [comment]
Hi guys, any news? Please let me know if I can do anything to assist!
![err](https://user-images.githubusercontent.com/1921603/57373246-37675f80-7198-11e9-9ed1-e3e75394d426.JPG)

**Comment by danieland** [comment]
Hi guys, still awaiting any updates on this - again please let me know if you need anymore information

**Comment by klarstrup** [comment]
Should be fixed as of `verso-browser@1.0.27`(included in `shopgun-sdk@2.3.16`)

**Comment by danieland** [comment]
Thanks for having a look @klarstrup ! Still seem to be getting this error though:

![2-3-16](https://user-images.githubusercontent.com/1921603/58539482-bd0a8800-81f7-11e9-9556-9e90d312b7a4.JPG)

- Cleared node_modules
- Updated SGN js sdk to 2.3.16
- Kept SGN css @ 2.3.14
- Ran new npm-install and checked verso-browser version to ensure 1.0.27:

> # Changelog
> ## Version 1.0.27
> * Update dependencies.

Also the total amount of lines seems to have changed (as you can see in the new error screenshot, the error comes from another line number now) so I assume this can also confirm I was in fact testing with 2.3.16

Please let me know if I missed something or forgot to update anything

**Comment by klarstrup** [comment]
Alright, I must've reproduced and fixed a separate bug related to starting and destroying. Can you share your source implementation of the opening/closing of the catalog?

**Comment by klarstrup** [comment]
These event handlers bound in `displayCatalog` of your `newspaperlist` component are not unbound in `closeCatalog`:
![image](https://user-images.githubusercontent.com/1567633/58545506-aec26900-8203-11e9-9602-83be2c473aa1.png)
![Screenshot 2019-05-29 at 11 20 06](https://user-images.githubusercontent.com/1567633/58545549-c7cb1a00-8203-11e9-9771-d6c412544d1b.png)

There is another such bug in `shopgun-sdk` that I will fix.

I'm adding a warning to verso-browser to help debug this in the future.

**Comment by klarstrup** [comment]
Warnings added in `verso-browser@1.0.28`, will fix `shopgun-sdk` now.

**Comment by klarstrup** [comment]
Alright, see if `shopgun-sdk@2.3.17` does the trick 😁

**Comment by danieland** [comment]
I cannot replicate with `shopgun-sdk@2.3.17` - nicely done @klarstrup  :)
